on rightclick holding a gold nugget:
  if clicked entity is not set:
    if name of event-item contains "デコイベル":
      if {pv.cooldown.%entity%::decoy_bell} is not set:
        set {pv.cooldown.%entity%::decoy_bell} to {DECOY_BELL_COOLDOWN}
        set {_loc} to event-player's location
        
        loop 10 times:
          play sound "block.bell.use" in player category with volume 3 and pitch 2 at {_loc}
          wait 1 seconds
